import {Platform, StyleSheet} from 'react-native';
import {COLORS} from '../../theme';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {IMAGES_RESIZE_MODES} from '../../constants/Common';
import {FONTS, getFontSize} from '../../theme';

export const styles = StyleSheet.create({
  shopContainer: {
    flex: 1,
  },
  headerBackImageStyle: {tintColor: COLORS.WHITE, height: 24, width: 24},
  scrollContainerStyle: {paddingBottom: 120},
  itemContainer: {
    // marginStart: wp('6%'),
    // marginEnd: wp('6%'),
  },
  dialogMessageContainer: {marginTop: 4, paddingHorizontal: wp('3.1%')},
  orderItemParentView: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.7%'),
    paddingTop: hp('1.2%'),
    paddingBottom: hp('1.2%'),
  },
  shipStatus: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: '500',
    fontFamily: 'SFProDisplay-Semibold',
    marginStart: wp('3%'),
  },
  shippedType: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontFamily: 'SFProDisplay-Medium',
    marginStart: wp('1%'),
    color: COLORS.BLACK_40,
  },
  orderStatus: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontWeight: 'normal',
    fontFamily: 'SFProDisplay-Regular',
  },
  orderStatusIcon: {alignSelf: 'flex-end'},
  orderListTopHeader: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.5%'),
    paddingTop: hp('2%'),
    paddingBottom: hp('2%'),
  },
  orderListHeaderWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  dateStyle: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Bold',
    ...Platform.select({
      android: {
        fontWeight: 'bold',
      },
    }),
  },
  topHeaderTitle: {
    fontSize: Platform.OS === 'ios' ? 19 : 17,
    fontFamily: 'SFProDisplay-Regular',
  },
  dateWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  reOrderTextStyle: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontWeight: '500',
    fontFamily: 'SFProDisplay-Medium',
    color: COLORS.MAIN,
  },
  divider: {
    borderBottomColor: COLORS.GRAY_1,
    borderBottomWidth: 1,
    marginTop: hp('.5%'),
    width: '94%',
    alignSelf: 'center',
    marginBottom: hp('1%'),
    marginStart: wp('6%'),
  },
  orderInfo: {
    // justifyContent: 'center',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  orderTypeText: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: 'bold',
    fontFamily: 'SFProDisplay-Semibold',
  },
  ordernumber: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Semibold',
    fontWeight: 'bold',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  locationTextStyle: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontWeight: '500',
    fontFamily: 'SFProDisplay-Regular',
    marginStart: wp('3%'),
  },
  productCard: {
    width: '80%',
    flexDirection: 'row',
    marginTop: hp('1.5%'),
    paddingBottom: hp('1.5%'),
    paddingTop: hp('1.5%'),
  },
  productCardParentView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '95%',
    alignSelf: 'flex-start',
  },
  productImage: {
    width: 100,
    height: 60,
    marginLeft: -8,
  },
  productInformationView: {
    width: '73%',
  },

  productDescriptionText: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    color: COLORS.BLACK,
  },
  billingAmountWrapper: {
    marginTop: hp('1%'),
    paddingBottom: hp('1%'),
  },
  billingTextWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  billingTextStyle: {
    color: COLORS.GRAY_TEXT,
    fontFamily: 'SFProDisplay-Regular',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
  },
  orderStatusTextStyle: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: 'normal',
    fontFamily: 'SFProDisplay-Regular',
  },
  orderStatusWrapper: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Semibold',
  },
  itemStatusWrapper: {
    marginTop: hp('2%'),
    backgroundColor: COLORS.WHITE,
    paddingTop: hp('1.2%'),
    paddingBottom: hp('1.2%'),
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemStatusInnerWrapper: {
    marginStart: wp('6%'),
    marginRight: wp('6%'),
    width: '78%',
  },
  textWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  trackingTextStyle: {
    color: COLORS.GRAY_67,
    marginTop: hp('1%'),
    fontSize: Platform.OS === 'ios' ? 16 : 14,
  },
  paymentTextWrapper: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: '600',
    fontFamily: 'SFProDisplay-Semibold',
  },
  cardInfoText: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: 'normal',
    fontFamily: 'SFProDisplay-Regular',
    marginTop: hp('1%'),
  },
  orderWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
  },
  orderTextStyle: {
    color: COLORS.MAIN,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
  },
  areaTextStyle: {
    fontSize: Platform.OS === 'ios' ? 16 : 14,
    fontWeight: 'normal',
    fontFamily: 'SFProDisplay-Regular',
  },
  toBeDelivered: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('5%'),
  },
  toBeDeliveredText: {
    color: COLORS.GRAY_5,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: '600',
    fontFamily: 'SFProDisplay-Regular',
  },
  toBeDeliveredDate: {
    color: COLORS.GRAY_5,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: '500',
    fontFamily: 'SFProDisplay-Regular',
  },
  airPortName: {
    color: COLORS.GRAY_67,
    fontSize: Platform.OS === 'ios' ? 16 : 14,
    fontWeight: 'normal',
    fontFamily: 'SFProDisplay-Regular',
  },
  pickedUpTimeText: {
    fontWeight: '500',
    fontSize: Platform.OS === 'ios' ? 15 : 13,
  },
  dateOuterWrapper: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.5%'),
    paddingHorizontal: wp('6%'),
    paddingVertical: hp('1.7%'),
  },
  dateInnerWrapper: {backgroundColor: COLORS.WHITE},
  dateHeaderText: {
    fontFamily: FONTS.BOLD,
    fontSize: getFontSize(18),
    letterSpacing: -0.35,
    color: COLORS.BLACK,
  },
  addressWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: hp('1.5%'),
  },
  listWrapper: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.7%'),
    paddingTop: hp('1.2%'),
  },
  substituteText: {
    color: COLORS.MAIN,
    fontSize: Platform.OS === 'ios' ? 14 : 13,
    marginTop: hp('1%'),
  },
  qtyTextWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('1.8%'),
  },
  qtyText: {
    color: COLORS.BLACK_40,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
  },
  priceDifferenceTextWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  priceDifferenceText: {
    color: COLORS.BLACK_40,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Medium',
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    textAlign: 'right',
  },
  storeAddressWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
  },
  btnWrapper: {
    width: '90%',
    backgroundColor: COLORS.DISABLE_BUTTON_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: 50,
    borderRadius: wp('2%'),
    marginTop: hp('3%'),
  },
  rightArrow: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  modalView: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  dialogView: {
    flex: 1,
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    paddingBottom: hp('5%'),
    maxHeight: hp('70%'),
  },
  dialogContent: {
    backgroundColor: 'white',
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    paddingBottom: hp('5%'),
    maxHeight: hp('50%'),
    maxWidth: wp('90%'),
    alignSelf: 'center',
  },
  listParentView: {
    flexDirection: 'row',
    width: '92%',
    paddingHorizontal: wp('2%'),
    paddingBottom: hp('1%'),
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  listRow: {
    width: '90%',
    marginTop: hp('0.5%'),
  },
  actionListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  radioUnchecked: {
    width: 17,
    height: 17,
    borderRadius: 9,
    borderColor: COLORS.BLACK,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.BLACK,
  },
  listInfoView: {
    marginStart: wp('1%'),
    alignItems: 'center',
    flexDirection: 'column',
  },
  itemName: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Medium',
    marginStart: wp('2.5%'),
  },
  descriptionText: {
    color: COLORS.GRAY_6,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
  },
  radioButtonView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  descriptionView: {
    flexDirection: 'row',
    width: '80%',
    marginStart: wp('7%'),
    marginTop: hp('.5%'),
  },
  itemNamesView: {
    flexDirection: 'row',
    marginStart: wp('2%'),
    width: '50%',
    height: 30,
  },
  separator: {
    alignSelf: 'center',
    height: 1,
    width: '94%',
    backgroundColor: COLORS.GRAY0_5,
    marginStart: widthPercentageToDP('6%'),
  },
  addIcon: {
    width: 9,
    height: 9,
    resizeMode: IMAGES_RESIZE_MODES.CONTAIN,
  },
  createListText: {
    color: COLORS.MAIN,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Medium',
    marginStart: wp('2%'),
  },
  labelText: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontFamily: 'SFProDisplay-Medium',
  },
  lebelInfo: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
    marginTop: hp('.5%'),
  },
  infoWrapper: {
    marginVertical: hp('1.2%'),
    justifyContent: 'center',
  },
  eligibleText: {
    fontFamily: 'SFProDisplay-Regular',
    fontSize: Platform.OS === 'ios' ? 20 : 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    color: '#000000',
  },
  itemsText: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Semibold',
    fontWeight: '600',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  priceTextStyle: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    // fontWeight: Platform.OS === 'ios' ? "500" : 'bold',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
    ...Platform.select({
      ios: {
        fontFamily: 'SFProDisplay-Regular',
      },
      android: {
        fontFamily: 'SFProDisplay-Medium',
      },
    }),
    lineHeight: 20,
    marginTop: hp('1%'),
    color: COLORS.BLACK,
  },
  rightArrowStyle: {
    width: 8,
    height: 25,
    alignSelf: 'flex-end',
  },
  textHeadingView: {
    fontFamily: 'SFProDisplay-Medium',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: Platform.OS === 'ios' ? '500' : 'bold',
    fontStyle: 'normal',
    lineHeight: 22,
    color: COLORS.BLACK,
  },
  subHeadingView: {
    fontFamily: 'SFProDisplay-Regular',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: 'normal',
    lineHeight: 20,
    color: COLORS.BLACK,
    marginTop: hp('.5%'),
  },
  customerInfo: {
    fontFamily: 'SFProDisplay-Semibold',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: Platform.OS === 'ios' ? '600' : 'bold',
    fontStyle: 'normal',
    lineHeight: 20,
    color: COLORS.BLACK,
  },
  deliveryWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  refunConfirmationDivider: {
    borderBottomColor: COLORS.GRAY_1,
    borderBottomWidth: 1,
    marginTop: hp('1%'),
    marginBottom: hp('1%'),
    marginStart: wp('6%'),
  },
  MainContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.OS === 'ios' ? 20 : 0,
  },

  Alert_Main_View: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#009688',
    height: 200,
    width: '90%',
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 7,
  },

  Alert_Title: {
    fontSize: 25,
    color: '#fff',
    textAlign: 'center',
    padding: 10,
    height: '28%',
  },

  Alert_Message: {
    fontSize: 22,
    color: '#fff',
    textAlign: 'center',
    padding: 10,
    height: '42%',
  },

  buttonStyle: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },

  TextStyle: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 22,
    marginTop: -5,
  },
  content: {
    backgroundColor: COLORS.DIALOG_BACKGROUND_COLOR,
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  contentTitle: {
    paddingTop: 22,
    fontFamily: 'SFProDisplay-Medium',
    fontSize: Platform.OS === 'ios' ? 19 : 17,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: -0.41,
    textAlign: 'center',
    color: '#030303',
  },
  otherReasonInstruction: {
    fontFamily: 'SFProDisplay-Regular',
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 16,
    letterSpacing: -0.08,
    textAlign: 'center',
    color: '#030303',
    marginTop: hp('1.5%'),
    marginStart: wp('10%'),
    marginEnd: wp('10%'),
  },
});
