import {APP_CONSTANTS} from '../../constants/Strings';
import {CAKE_TYPES} from '../../constants/Common';

const WRITTEN_MESSAGE_MAX_LENGTH = 30;

export const CAKE_INFO_KEYS = {
  FILLING: 'FILLING',
  FLAVOR: 'FLAVOR',
  DECORATION_TYPE: 'DECORATION_TYPE',
  DECORATION_DESC: 'DECORATION_DESC',
  WRITTEN_MESSAGE: 'WRITTEN_MESSAGE',
  SPECIAL_INSTRUCTION: 'SPECIAL_INSTRUCTIONS',
  FROSTING_FLAVOR: 'FROSTING_FLAVOR',
  FROSTING_DESC: 'FROSTING_DESC',
  CAKE_FLAVOR: 'CAKE_FLAVOR',
};

export const CAKE_MODALS_INFO = {
  [CAKE_INFO_KEYS.FILLING]: {
    title: APP_CONSTANTS.CAKE_FILLING,
    buttonTitle: APP_CONSTANTS.SELECT,
    dataKey: 'Cake Filling',
  },
  [CAKE_INFO_KEYS.CAKE_FLAVOR]: {
    title: APP_CONSTANTS.CAKE_FLAVOR,
    buttonTitle: APP_CONSTANTS.SELECT,
    cupCakeTitle: APP_CONSTANTS.CUPCAKE_FLAVOR,
    dataKey: 'Cake Flavor',
  },
  [CAKE_INFO_KEYS.DECORATION_TYPE]: {
    title: APP_CONSTANTS.EDITABLE_DECORATION,
    buttonTitle: APP_CONSTANTS.SELECT,
    dataKey: 'DecorationTypes',
  },
  [CAKE_INFO_KEYS.DECORATION_DESC]: {
    title: APP_CONSTANTS.ENTER_REQUEST,
    description: APP_CONSTANTS.EDIBLE_DECORATION_REQUEST_DESCRIPTION,
    placeHolder: APP_CONSTANTS.ENTER_EDIBLE_DECORATION_REQUEST,
    buttonTitle: APP_CONSTANTS.DONE,
    maxLength: WRITTEN_MESSAGE_MAX_LENGTH,
  },
  [CAKE_INFO_KEYS.WRITTEN_MESSAGE]: {
    title: APP_CONSTANTS.WRITTEN_MESSAGE,
    placeHolder: APP_CONSTANTS.ENTER_MESSAGE_II,
    buttonTitle: APP_CONSTANTS.DONE,
    maxLength: WRITTEN_MESSAGE_MAX_LENGTH,
  },
  [CAKE_INFO_KEYS.SPECIAL_INSTRUCTION]: {
    title: APP_CONSTANTS.SPECIAL_INSTRUCTIONS,
    placeHolder: APP_CONSTANTS.ENTER_SPECIAL_INSTRUCTIONS_I,
    buttonTitle: APP_CONSTANTS.DONE,
  },
  [CAKE_INFO_KEYS.FROSTING_DESC]: {
    title: APP_CONSTANTS.OTHER_FROSTING_FLAVOR,
    placeHolder: APP_CONSTANTS.FROSTING_FLAVOR_PLACEHOLDER,
    description: APP_CONSTANTS.ENTER_FROSTING_FLAVOUR_DESCRIPTION,
    buttonTitle: APP_CONSTANTS.DONE,
    maxLength: WRITTEN_MESSAGE_MAX_LENGTH,
  },
  [CAKE_INFO_KEYS.FROSTING_FLAVOR]: {
    title: APP_CONSTANTS.FROSTING_FLAVOR,
    buttonTitle: APP_CONSTANTS.SELECT,
    dataKey: 'FROSTING_FLAVOR',
  },
};

export const DECORATION_DATA_KEYS = {
  EMAIL_STORE: 'EMAIL_TO_STORE',
  ENTER_REQUEST: 'ENTER_REQUEST',
};

export const DECORATION_DATA = [
  {DecorationTypes: APP_CONSTANTS.EMAIL_IMAGE_TO_STORE, key: DECORATION_DATA_KEYS.EMAIL_STORE, isRightArrow: true},
  {
    DecorationTypes: APP_CONSTANTS.ENTER_EDIBLE_DECORATION_REQUEST,
    key: DECORATION_DATA_KEYS.ENTER_REQUEST,
    isRightArrow: true,
  },
];

export const CAKE_OPTIONS_INFO = {
  [CAKE_INFO_KEYS.CAKE_FLAVOR]: {
    title: APP_CONSTANTS.CAKE_FLAVOR,
    description: APP_CONSTANTS.SELECT_FLAVOR,
    key: CAKE_INFO_KEYS.CAKE_FLAVOR,
  },
  [CAKE_INFO_KEYS.FILLING]: {
    title: APP_CONSTANTS.CAKE_FILLING,
    description: APP_CONSTANTS.SELECT_FILLING,
    key: CAKE_INFO_KEYS.FILLING,
  },
  [CAKE_INFO_KEYS.DECORATION_TYPE]: {
    title: APP_CONSTANTS.EDITABLE_DECORATION,
    description: APP_CONSTANTS.SELECT_DECORATION,
    key: CAKE_INFO_KEYS.DECORATION_TYPE,
  },
  [CAKE_INFO_KEYS.WRITTEN_MESSAGE]: {
    title: APP_CONSTANTS.WRITTEN_MESSAGE,
    description: APP_CONSTANTS.ENTER_MESSAGE,
    key: CAKE_INFO_KEYS.WRITTEN_MESSAGE,
  },
  [CAKE_INFO_KEYS.SPECIAL_INSTRUCTION]: {
    title: APP_CONSTANTS.SPECIAL_INSTRUCTIONS,
    description: APP_CONSTANTS.ENTER_SPECIAL_INSTRUCTIONS,
    key: CAKE_INFO_KEYS.SPECIAL_INSTRUCTION,
  },
  [CAKE_INFO_KEYS.FROSTING_FLAVOR]: {
    title: APP_CONSTANTS.FROSTING_FLAVOR,
    description: APP_CONSTANTS.SELECT_FLAVOR,
    key: CAKE_INFO_KEYS.FROSTING_FLAVOR,
  },
};

export const CAKE_OPTIONS = {
  [CAKE_TYPES.SHEET_CAKE]: [
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.CAKE_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.FROSTING_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.WRITTEN_MESSAGE],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.SPECIAL_INSTRUCTION],
  ],
  [CAKE_TYPES.CUPCAKE]: [
    {...CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.CAKE_FLAVOR], title: APP_CONSTANTS.CUPCAKE_FLAVOR},
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.FROSTING_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.SPECIAL_INSTRUCTION],
  ],
  [CAKE_TYPES.FILLED_SHEET_CAKE]: [
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.CAKE_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.FILLING],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.FROSTING_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.WRITTEN_MESSAGE],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.SPECIAL_INSTRUCTION],
  ],
  [CAKE_TYPES.DECORATED_CAKE]: [
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.CAKE_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.FROSTING_FLAVOR],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.DECORATION_TYPE],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.WRITTEN_MESSAGE],
    CAKE_OPTIONS_INFO[CAKE_INFO_KEYS.SPECIAL_INSTRUCTION],
  ],
};

export const DIALOG_BOX_KEYS = {
  CAKE_LEAD_TIME: 'CAKE_LEAD_TIME',
  EMAIL_DECORATION: 'EMAIL_DECORATION',
  API_ERROR: 'API_ERROR',
};

export const DIALOG_BOX_DATA = {
  [DIALOG_BOX_KEYS.API_ERROR]: {
    title: APP_CONSTANTS.ALASKA_COMMERCIAL,
    message: APP_CONSTANTS.SOME_THING_WENT_WRONG,
    isSingleButton: false,
    leftButtonTitle: APP_CONSTANTS.CANCEL,
    rightButtonTitle: APP_CONSTANTS.RETRY,
  },
  [DIALOG_BOX_KEYS.EMAIL_DECORATION]: {
    title: APP_CONSTANTS.EMAIL_IMAGE_INSTRUCTIONS,
    message: APP_CONSTANTS.DECORATION_EMAIL_INSTRUCTIONS_I,
    isSingleButton: true,
    leftButtonTitle: APP_CONSTANTS.OKAY,
    rightButtonTitle: APP_CONSTANTS.OKAY,
  },
  [DIALOG_BOX_KEYS.CAKE_LEAD_TIME]: {
    title: APP_CONSTANTS.CUSTOM_CAKE_LEAD_TIME,
    message: APP_CONSTANTS.CAKE_LEAD_TIME_MESSAGE,
    isSingleButton: false,
    leftButtonTitle: APP_CONSTANTS.CANCEL,
    rightButtonTitle: APP_CONSTANTS.OKAY,
  },
};
