import {StyleSheet} from 'react-native';
import {heightPercentageToDP as hp, widthPercentageToDP as wp} from 'react-native-responsive-screen';

import {COLORS} from '../../theme';
import {FONTS, getFontSize} from '../../theme';

export const styles = StyleSheet.create({
  shopContainer: {
    flex: 1,
  },
  dateStyle: {
    fontSize: getFontSize(18),
    fontFamily: FONTS.BOLD,
    letterSpacing: -0.35,
    color: COLORS.BLACK,
  },
  dateWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  reOrderTextStyle: {
    fontSize: getFontSize(13),
    fontFamily: FONTS.MEDIUM,
    color: COLORS.MAIN,
    letterSpacing: -0.26,
  },
  divider: {
    borderBottomColor: COLORS.GRAY_1,
    borderBottomWidth: 1,
    marginTop: hp('.5%'),
  },
  orderNumber: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.BOLD,
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
    lineHeight: 20,
    letterSpacing: -0.24,
    color: COLORS.BLACK,
  },
  orderStatusTextStyle: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.REGULAR,
    lineHeight: 20,
    letterSpacing: -0.24,
    color: COLORS.BLACK,
  },
  orderStatusWrapper: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.SEMI_BOLD,
    lineHeight: 20,
    letterSpacing: -0.24,
    color: COLORS.BLACK,
  },
  itemStatusWrapper: {
    marginTop: hp('2%'),
    backgroundColor: COLORS.WHITE,
    paddingTop: hp('1.2%'),
    paddingBottom: hp('1.2%'),
  },
  itemStatusInnerWrapper: {
    marginStart: wp('6%'),
    marginRight: wp('6%'),
    fontSize: getFontSize(14),
    lineHeight: 20,
    letterSpacing: -0.19,
    color: COLORS.CHARCOAL_GREY_60,
  },
  textWrapper: {
    marginStart: wp('6%'),
    marginRight: wp('6%'),
  },
  trackingTextStyle: {
    color: COLORS.GRAY_67,
    marginTop: hp('1%'),
    fontSize: getFontSize(14),
    marginStart: wp('6%'),
    fontFamily: FONTS.REGULAR,
  },
  cardInfoText: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.REGULAR,
    marginTop: hp('1%'),
    lineHeight: 20,
    letterSpacing: -0.24,
    color: COLORS.BLACK,
  },
  orderTextStyle: {
    color: COLORS.MAIN,
    fontSize: getFontSize(15),
    fontFamily: FONTS.SEMI_BOLD,
    // lineHeight: 22,
    letterSpacing: -0.35,
    marginStart: wp('1%'),
  },
  orderPickedDate: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.MEDIUM,
    letterSpacing: 0,
    textAlign: 'right',
    color: COLORS.BLACK,
  },
  areaTextStyle: {
    fontSize: getFontSize(14),
    fontFamily: FONTS.REGULAR,
    letterSpacing: -0.2,
    color: COLORS.BLACK,
    marginStart: wp('1%'),
    marginTop: hp('1%'),
  },
  toBeDeliveredText: {
    color: COLORS.GRAY_5,
    fontSize: getFontSize(15),
    fontFamily: FONTS.SEMI_BOLD,
    lineHeight: 22,
    letterSpacing: -0.35,
    marginTop: hp('2.4%'),
    marginStart: wp('1%'),
  },
  toBeDeliveredDate: {
    color: COLORS.GRAY_5,
    fontSize: getFontSize(15),
    fontFamily: FONTS.MEDIUM,
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'right',
    marginTop: hp('2.4%'),
  },
  pickedUpTimeText: {
    fontFamily: FONTS.MEDIUM,
    fontSize: getFontSize(13),
    lineHeight: 22,
    letterSpacing: -0.31,
    color: COLORS.BLACK,
  },
  dateOuterWrapper: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.5%'),
    paddingTop: hp('1.7%'),
    paddingBottom: hp('1.7%'),
  },
  listWrapper: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.7%'),
    paddingTop: hp('1.2%'),
    paddingBottom: hp('1.2%'),
  },
  payment: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.SEMI_BOLD,
    lineHeight: 22,
    letterSpacing: -0.36,
    color: COLORS.BLACK,
  },
  orderStatusInnerWrapper: {
    marginTop: hp('2%'),
    marginStart: wp('4%'),
    marginEnd: wp('6%'),
    justifyContent: 'center',
  },
  modalText: {
    color: COLORS.BLACK,
    fontFamily: FONTS.REGULAR,
    marginHorizontal: wp('6%'),
    fontSize: getFontSize(15),
    lineHeight: 24,
  },
  dialogBoxMessage: {
    paddingHorizontal: 15,
    marginTop: 5,
  },
  errorText: {
    marginTop: 15,
    fontFamily: FONTS.REGULAR,
    fontSize: getFontSize(15),
  },
  errorImage: {
    width: 100,
    height: 100,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  separator: {
    marginStart: wp('6%'),
    height: 0.5,
    width: '100%',
    backgroundColor: '#C8C8C8',
  },
});
