import {APP_CONSTANTS} from './Strings';
import {PAYMENT_METHODS} from './Common';

export const MIX_PANEL_PAYMENTS = {
  [PAYMENT_METHODS.EIGEN]: 'CC/DC',
  [PAYMENT_METHODS.SNAP_CASH]: 'SNAP Cash',
  [PAYMENT_METHODS.SNAP_FOOD]: 'SNAP Food',
  [PAYMENT_METHODS.VIRTUAL_WALLET]: APP_CONSTANTS.VIRTUAL_WALLET,
  [PAYMENT_METHODS.GIFT_CARD]: APP_CONSTANTS.GIFT_CARD,
  [PAYMENT_METHODS.STORE_CHARGE]: APP_CONSTANTS.STORE_CHARGE_ACCOUNT,
};
export const MIX_PANEL_SCREENS = {
  SEARCH: 'Search',
  SHOP: 'Shop',
  ON_SALE: 'Sale',
  HOME: 'Home',
  LIST: 'List',
  CART: 'Cart',
  DEEP_LINK: 'DeepLink',
  ITEMS_YOU_MAY_LIKE: 'Items You May Like',
  PRODUCT_DETAILS: 'Details',
  CAKE_DETAILS: 'Details',
};
export const MIX_PANEL_EVENTS = {
  SEARCH: 'Search',
  LOGIN: 'Login',
  VIEW_ITEM_DETAIL_PAGE: 'View Item Detail Page',
  ADD_ITEM_TO_MY_LIST: 'Add Item to My List',
  COMPLETE_PURCHASE: 'Complete Purchase',
  COMPLETE_REGISTRATION: 'Complete Registration',
  VIEW_CHECKOUT_PAGE: 'View Checkout Page',
  ADD_ITEM_TO_CART: 'Add Item to Cart',
  VISIT: 'Visit',
  HERO_BANNER: 'Promotion',
};
export const MIX_PANEL_PROPS = {
  SKU: 'SKU',
  ENTRY_POINT: 'Entry Point',
  MY_LIST_NAME: 'My List Name',
  ITEM_NAME: 'Item Name',
  ITEM_DEPARTMENT: 'Item Department',
  ITEM_SUB_DEPARTMENT: 'Item Sub-department',
  ITEM_COST: 'Item Cost',
  RW: 'RW?',
  MOBILE: 'Mobile',
  UOM: 'UOM?',
  ITEMS_YOU_MIGHT_LIKE: 'Items you might like?',
  SALE_ITEM: 'Sale Item?',
  UPC: 'UPC',
  ITEM_QUANTITY: 'Item Quantity',
  PHONE_NUMBER: 'Phone Number',
  ZIP_CODE: 'Zip Code',
  LOW_BANDWIDTH: 'Low Bandwidth',
  STORE_LOCATION: 'Store Location',
  VILLAGE: 'Village',
  IS_GUEST: 'Is Guest',
  IP_ADDRESS: 'IP Address',
  OF_SEARCHES: '# of Searches',
  SEARCH_TERM: 'Search Term',
  SEARCH_CHARACTER_LENGTH: 'Search Character Length',
  OF_RESULTS_RETURNED: '# of Results Returned',
  LOGIN_METHOD: 'Login Method',
  CART_SIZE: 'Cart Size',
  CART_VALUE: 'Cart Value',
  CART_ITEM_UPCS: 'Cart Item UPCs',
  CART_ITEM_DEPARTMENTS: 'Cart Item Departments',
  CART_ITEM_SUB_DEPARTMENTS: 'Cart Item Sub-departments',
  CART_ITEM_NAMES: 'Cart Item Names',
  DELIVERY_METHOD: 'Delivery Method',
  ESTIMATED_TOTAL_AMOUNT: 'Estimated Total Amount',
  CART_DETAILS_ALL: 'Cart Details (All)',
  REGISTRATION_DATE: 'Registration Date',
  PAGE_NAME: 'Page Name',
  PLATFORM: 'Platform',
  APP_VERSION: 'App Version',
  PAGE_VARIANT: 'Page Variant',
  DELIVERY_AMOUNT: 'Delivery Amount',
  CART_DETAILS: 'Cart Details',
  STORE: 'Store',
  STORE_NUMBER: 'Store Number',
  TOTAL_AMOUNT: 'Total Amount',
  TAX_AMOUNT: 'Tax Amount',
  PAYMENT_TYPE: 'Payment Type',
  LIFETIME_VALUE: 'Lifetime Value',
  SMS_MARKETING: 'SMS Marketing',
  EMAIL_MARKETING: 'Email Marketing',
  ALLOW_SUBSTITUTION: 'Allow Substitution',
  USER_TOKEN: 'User Token',
  SLOT: 'Slot',
  LOCATION: 'Location',
  PROMOTIONAL_ID: 'Promotion ID',
  PROMOTIONAL_NAME: 'Promotion Name',
  PROMOTIONAL_IMAGE: 'Promotion Image',
  PROMOTIONAL_LINK: 'Promotion Link',
  PROMOTIONAL_TEXT: 'Promotion Text',
};
