export const APP_CONSTANTS = {
  APP_NAME: 'Alaska Commercial',
  WELCOME: 'Welcome',
  HI: 'Hi',
  SINGLE_SPACE: ' ',
  DOUBLE_SPACE: '  ',
  HOME: 'Home',
  ON_SALE: 'On Sale',
  APP_ONLY: 'App Only',
  DEALS: 'Deals',
  LIST: 'List',
  ERROR: 'Error',
  DOWNLOAD: 'Download',
  FACE_ID: 'Face ID',
  TOUCH_ID: 'Touch ID',
  FACE_ID_R: 'Face ID®',
  TOUCH_ID_R: 'Touch ID®',
  BIOMETRIC: 'Biometric',
  APP_UPDATE_AVAILABLE: 'App Update Available',
  APP_UPDATE_REQUIRED: 'App Update Required',
  APP_UPDATE_AVAILABLE_MESSAGE_FORCE:
    'An update to the Alaska Commercial app is required to continue.',
  APP_UPDATE_AVAILABLE_MESSAGE:
    'Alaska Commercial recommends updating to the latest version of this shopping app.',
  APP_UNDER_MAITENANCE: 'We’re performing maintenance right now',
  APP_UNDER_MAITENANCE_MESSAGE:
    'We’re making updates to improve your online payment experience. Please check back in a few hours.',
  ONLINE_SNAP_COMING_SOON: 'Online SNAP Coming Soon',
  EBT_CARD_ALERT: 'Payment Method Alert',
  STA_COMING_SOON: 'AC Store Charge Accounts Coming Soon',
  STA_COMING_SOON_MESSAGE:
    'We’re working on updates that will allow us to accept AC Store Charge Account payments for online orders.',
  HISTORY: 'History',
  CLOSED: 'Closed',
  LOGIN: 'Login',
  EMAIL: 'Email',
  SKIP: 'Skip',
  EMAIL_ADDRESS: 'Email Address',
  PASSWORD: 'Password',
  CONFIRM_PASS: 'Confirm Password',
  FORGOT_PASS: 'Forgot Password?',
  SIGN_IN: 'Sign In',
  GUEST_NAME:'Guest',
  GUEST: 'Continue as Guest',
  NOT_MEMBER_TEXT: 'Not a member? ',
  CREATE_NEW_ACC: 'Create a new account',
  LOGIN_EMAIL_ERROR: 'Please enter valid email address and/or password',
  EMAIL_INPUT_ERROR: 'Please enter a valid email address',
  CREATE_ACCOUNT: 'Create Account',
  F_NAME: 'First Name',
  L_NAME: 'Last Name',
  C_NUMBER: 'Phone Number',
  SIGNUP_PASSWORD_REQUIREMENT:
    'Password must be at least 8 characters and contain 1 special character, 1 capital letter, and 1 number.',
  FORGOT_PASSWORD_REQUIREMENT:
    'Password Requirement: Minimum 8 characters including at least 1 special character, 1 capital letter, and 1 number.',
  COUPONS_AND_DEALS: 'Allow notifications',
  TERMS: 'Terms of Use',
  AGREEMENT: "I agree with Alaska Commercial's ",
  AND: ' and ',
  PRIVACY_POLICY: 'Privacy Policy',
  CONTINUE: 'Continue',
  CONTINUE_TO_PAYMENT: 'Continue to Payment',
  SIGNUP_EMAIL_ERROR: 'Please enter valid email address',
  PASS_REQ_ERR: 'Enter a password that meets the requirements',
  PASS_NO_MATCH: 'Password does not match',
  SIGN_UP_FOR_EMAIL_MARKETING: 'Sign up for Email Marketing',
  SIGN_UP_FOR_SMS_MARKETING: 'Sign up for SMS Marketing',
  ZIP_CODE: 'Zip Code',
  ZIP_CODE_INSTRUCTIONS:
    'Please enter your zip code to determine the default store.',
  CONFIRM: 'Confirm',
  SELECT_STORE: 'Select Store',
  PREFERENCES: 'Preferences',
  TERMS_OF_SERVICE: 'TERMS OF SERVICE',
  LOCATION_N_BANDWIDTH: 'Location and Bandwidth Preferences',
  LOCATION: 'Location',
  LOCATION_INSTRUCTIONS: 'Find Nearby Stores',
  CITY_STATE_ZIP_CODE: 'City, State or Zip Code',
  SAVE: 'Save',
  SELECT_MARKETING_OPTIONS: 'Select Marketing Options',
  PAYMENT_METHOD: 'Payment Method',
  ADD_SNAP_CARD: 'Add EBT Card',
  RETRIEVE_SNAP_BALANCE_TITLE:
    'Please enter your PIN to retrieve your current EBT balance',
  RETRIEVE_SNAP_CASH_BALANCE_TITLE:
    'Please enter your PIN to retrieve your current EBT Cash balance',
  SAVE_SNAP_CARD: 'Retrieve Balance and SAVE Card',
  ADD_GIFT_CARD: 'Add Gift Card',
  GC_BALANCE: 'Gift Card Balance',
  GC_OPTIONS: 'Gift Card Options',
  SAVE_GIFT_CARD: 'Save Gift Card',
  RETRIEVE_GC_BALANCE: 'Retrieve Balance and Save Gift Card',
  RETRIEVE_GC_BALANCE_SUBMIT: 'Retrieve Balance and Submit',
  RETRIEVE_BALANCE: 'Retrieve Balance',
  RETRIEVE_SNAP_BALANCE: 'Retrieve EBT Card Balance',
  RETRIEVE_EBT_CASH_BALANCE: 'Retrieve EBT Cash Balance',
  SUBMIT_VW_PAYMENT: 'Submit Virtual Wallet Payment',
  RETRIEVE_SNAP_BALANCE_SINGLE_USE:
    'Retrieve balance and add to this transaction only',
  PIN_TO_CONFIRM: 'Please enter your PIN to confirm',
  ADD_AC_GIFT_CARD: 'Add AC Gift Card',
  ADD_STORE_CHARGE_ACCOUNT: 'Add Store Charge Account',
  APPLY_FULL_ELIGIBLE_AMOUNT: 'Apply Full Eligible Amount',
  ENTER_AMOUNT_C: 'Enter Amount',
  SNAP_BALANCE: 'EBT Card Balance',
  FOOD_BENEFIT: 'Food Balance',
  CASH_BENEFIT: 'Cash Balance',
  FORGOT_PASS_INSTRUCTIONS:
    'Enter your email or phone number for the verification process and we will send a link to reset your password. ',
  PASSWORD_RECOVERY: 'Password Recovery',
  SEND: 'Send',
  LOW_BANDWIDTH: 'Low Bandwidth',
  SALE_ITEMS: 'Sale Items',
  DEPARTMENTS: 'Departments',
  FEATURED_CATEGORIES: 'Featured Categories',
  SEE_ALL: 'See All',
  VIEW_ALL: 'View All',
  SEARCH_ITEMS: 'Search Items',
  CREATE_NEW_LIST: 'Create New List',
  CREATE_LIST_DESCRIPTION: 'Add a list by creating a name.',
  LIST_NAME: 'List Name',
  MORE: 'More',
  DUPLICATE: 'Duplicate',
  DUPLICATE_LIST: 'Duplicate List',
  RENAME: 'Rename',
  EDIT: 'Edit',
  ADD_ALL: 'Add All',
  ADDED_ALL: 'Added All',
  REMOVE_ALL: 'Remove All',
  ADD: 'Add',
  ADD_: 'ADD',
  ADDED: 'Added',
  DELETE: 'Delete',
  DELETE_LIST: 'Delete List',
  DELETE_CARD: 'Delete Card',
  DELETE_CARD_CONFIRMATION: 'Are you sure you want to delete this card?',
  NO_ITEMS_IN_LIST: 'No Items in List',
  USDA_MESSAGE:
    'The USDA doesn’t allow freight to be paid with SNAP benefits. Please choose another payment type for freight and handling.',
  NOTIFICATIONS: 'Notifications',
  SETTINGS: 'Settings',
  IN_APP: 'In-App',
  TEXT: 'Text',
  ALERT: 'Alert',
  SALE: 'Sale',
  PROFILE: 'Profile',
  NAME: 'Name',
  ADDRESS: 'Address',
  PHONE_NUM: 'Phone Number',
  SHOP: 'Shop',
  PAYMENT: 'Payment',
  MY_LIST: 'My List',
  CHANGE_PASS: 'Change Password',
  STORE: 'Store',
  STATE: 'State',
  CITY: 'City',
  ACCOUNT: 'Account',
  SHARE_LOCATION: 'Share My Location',
  RETURN: 'Return',
  CONTACT_US: 'Contact Us',
  ABOUT: 'About',
  LOGOUT: 'Log out',
  VIRTUAL_WALLET: 'Virtual Wallet',
  VIRTUAL_WALLET_ACCOUNT: 'Virtual Wallet Account',
  REFUND: 'Refund Request',
  SELECT_TOPIC: 'Select Topic',
  STORE_LOCATION: 'Store Location',
  ITEMS_TO_LIST:
    'As our store reviews your shared items, they will be moved to your Lists.',
  CLICK_HERE: 'Click Here',
  SNAP_ORDER: 'SNAP Order',
  MOVE_TO_LIST: 'Move to List',
  SUCCESS: 'Success!',
  SHARE: 'Share',
  SHARE_ITEMS: 'Share Items',
  SHARE_ITEMS_TEXT:
    'You can share list items with your AC store or an external email address.',
  ADD_MESSAGE_TO_STORE: 'Add message to Store (optional)',
  SHARE_ITEMS_WITH_STORE_CONFIRM_TEXT_I:
    'Clicking Confirm will send your list to',
  SHARE_ITEMS_WITH_STORE_DESCRIPTION:
    'Click here to send your item list to the store. Use this option if you would like confirmation by phone of your items before adding them to the cart and finalizing your order.',
  SHARE_ITEMS_EXTERNAL_EMAIL_DESCRIPTION:
    'Click Here to send your item list to an external email address. Use this option if you would like to email your list to yourself or to someone else.',
  SHARE_ITEMS_WITH_STORE_CONFIRM_TEXT_II:
    'Please select EBT Order below if you plan to use EBT as a payment method. The store will contact you by email or phone in 1-3 business days.',
  SHARE_ITEMS_WITH_STORE: 'Share Items with Store',
  SHARE_ITEMS_WITH_EXTERNAL_EMAIL: 'Share Items with External Email',
  ADD_MESSAGE_OPTIONAL: 'Add message (optional)',
  LIST_SHARED_WITH_EMAIL: 'Your List Items have been shared with',
  SHARE_ITEMS_WITH_STORE_CONFIRMED:
    'Your Cart Items have been shared with STORE. The STORE team will contact you by email or phone in 1 - 3 business days to confirm your order.',
  SHARE_ITEMS_WITH_STORE_TEXT:
    ' to send your item list to the store instead of proceeding through the rest of the checkout and payment process. Use this option if you want to pay with EBT benefits or if you would like the store to confirm your order before finalizing.',
  ELIGIBLE_FOR_REFUND: 'Orders Eligible for Refund',
  REFUND_REQUEST: 'REFUND REQUEST',
  COMMUNICATION_SETTINGS: 'Communication Settings',
  ORDER_UPDATES: 'Order Updates',
  MARKETING_UPDATES: 'Marketing Updates',
  EMAIL_MARKETING: 'Email Marketing',
  TEXT_MARKETING: 'Text Marketing',
  FORGOT_PASS_HEADER: 'Forgot Password',
  INVALID_ZIP_CODE:
    'Invalid zip code, no stores found. Please enter a valid zip code.',
  SOME_THING_WENT_WRONG: 'Oops! Something went wrong. Please try again later',
  CHECKOUT_FAILED_MESSAGE:
    'Oops! Something went wrong.\n Please do not re-submit your order. Call Customer Operations at 1-844-672-4274 or submit a Contact Us ticket with the topic,\n “I have a technical issue with the app/website.”',
  SNAP_FEATURE_MESSAGE:
    'In the meantime, please email your EBT/SNAP order to your AC store by creating a List and selecting Share List with Store.',
  PAYMENT_FULFILLED:
    'You have allocated full amount to the Estimated Order Total.',
  SINGLE_GC_ALLOWED:
    'An AC Gift Card has already been applied to this order. Only one AC Gift Card can be applied to an order.',
  SINGLE_STA_ALLOWED:
    'A Store Charge Account has already been applied to this order. Only one Store Charge Account can be applied to an order.',
  INSUFFICIENT_BALANCE: 'Insufficient Balance',
  EMAIL_IS_ALREADY_VERIFIED: 'Email is already verified.',
  EMAIL_VERIFIED: 'Email has been verified.',
  ADD_PAYMENT_METHODS: 'Add One or more Payment Methods',
  SAVED_PAYMENT_METHODS: 'Saved Payment Methods',
  SAVED_PAYMENT_METHOD: 'Saved Payment Method',
  AVAILABLE_PAYMENT_METHODS: 'Available Payment Methods',
  ADD_NEW_PAYMENT_METHOD: 'Add New Payment Method',
  CONTINUE_TO_CHECKOUT: 'Continue to Checkout',
  ADD_ANOTHER_PAYMENT_METHODS:
    'Please provide another payment method for the remaining',
  ALASKA_COMMERCIAL: 'Alaska Commercial Company',
  ACCOUNT_DEACTIVATED_TEXT:
    'Your Alaska Commercial Company account has been deactivated. Please contact Customer Service if you have further questions. Thank you for shopping with us!',
  ALASKA_COMMERCIAL_COMPANY: 'Alaska Commercial Company',
  ARE_YOU_SURE: 'Are you sure?',
  FREIGHT_CHARGE_PAYMENT: 'Freight Charge Payment',
  OK: 'OK',
  OKAY: 'Okay',
  RETRY: 'Retry',
  ZIP_CODE_CHANGED: 'Default store location has been updated to ',
  SETTINGS_HEADER: 'SETTINGS',
  SHOP_HEADER: 'SHOP',
  LIST_HEADER: 'LIST',
  SALE_HEADER: 'SALE',
  DEALS_HEADER: 'DEALS',
  ORDER_HISTORY: 'ORDER HISTORY',
  NOTIFICATION_HEADER: 'NOTIFICATIONS',
  ABOUT_HEADER: 'ABOUT',
  PROFILE_HEADER: 'PROFILE',
  PREFERENCE_HEADER: 'PREFERENCES',
  DEACTIVATE_ACCOUNT: 'Deactivate Account',
  DEACTIVATE_ACCOUNT_MESSAGE:
    'Are you sure you would like to deactivate your account? \n' +
    'Note: Your data may be retained for up to 90 days during the deletion process',
  PAY_FREIGHT_TO_AIRLINE:
    'I would like to pay the airline directly for my freight charges',
  PAY_FREIGHT_TO_AIRLINE_CONFIRMATION:
    'Selecting this option means that you are responsible for paying the airline before your order can ship. AC is not responsible for orders that are not shipped due to non-payment. Please confirm.',
  YES: 'Yes',
  NO: 'No',
  NO_RECORD: 'No Record found',
  NO_NEW_NOTIFICATION: 'No New Notifications',
  NO_RECORD_MESSAGE: 'There is no item for this search',
  NO_RECORD_MESSAGE_FOR_SALE: 'There is no department on sale',
  NO_ITEM_FOUND: 'No Item Found',
  OTHER_REASON: 'Refund Reason - Other',
  OTHER_REASON_INSTRUCTION:
    'You must speak with a Customer Service Representative before submitting this Refund Request.',
  CONTACT_CUSTOMER_SERVICE: 'Contact Customer Service',
  RETURN_TO_REFUND: 'Return to Refund Request',
  WALLET_MODAL: 'Virtual Wallet',
  DONE: 'Done',
  ACCOUNT_NUMBER: 'Account Number',
  AVAILABLE: 'available',
  CANCEL: 'Cancel',
  ENABLE: 'Enable',
  DISABLE: 'Disable',
  CANCEL_ORDER: 'Cancel Order',
  CONFIRM_CANCEL_ORDER:
    'Are you sure you want to cancel your order? This action will remove all items from the shopping cart.',
  CREATE: 'Create',
  RENAME_LIST: 'Rename List',
  RENAME_LIST_DESCRIPTION: 'Rename list by choosing new name',
  ABOUT_US: 'About Us',
  FAQS: 'FAQs',
  SHIPPING_AND_FREIGHT: 'Shipping, Refunds & Returns',
  CONTACT_US_HEADER: 'CONTACT US',
  WE_LOVE_TO_HEAR: "We'd love to hear from you!",
  CONTACT_US_SUBHEADER:
    'Help us create a better experience for our customers. Send us your comments, questions, suggestions, requests, and any other feedback you think we should hear!',
  SUBMIT: 'Submit',
  NEW_NOTIFICATIONS: 'New Notifications',
  PAST_NOTIFICATIONS: 'Past Notifications',
  NO_STORE_FOUND: 'Invalid zip code, no stores found',
  LOGOUT_MESSAGE: 'Are you sure you want to logout?',
  ADVANCE_SEARCH: 'Advance Search',
  FILTER_BY: 'Filter by',
  FILTER: 'Filter',
  CLEAR_ALL: 'Clear All',
  DEPARTMENT: 'Department',
  SORT_BY: 'Sort by',
  LOW_TO_HIGH: 'Low to High',
  HIGH_TO_LOW: 'High to Low',
  PRICE: 'Price',
  UPDATE: 'Update',
  SALE_TYPE: 'Sale Type',
  VERIFICATION_CODE_INSTRUCTIONS:
    'Please enter the 6 digit verification code received via email or text.',
  ADDITIONAL_SAVINGS: 'Additional Savings',
  ADDITIONAL_SAVINGS_DIALOG_MESSAGE:
    'Would you like to create an account to get additional savings?',
  RESET_PASSWORD_INSTRUCTIONS:
    'Set the new password for your account so you can login and access all features.',
  CHANGE_PASSWORD_INSTRUCTIONS:
    'Please set the new password for your account following the below requirement.',
  GUEST_FEATURE_RESTRICTION_MESSAGE:
    'This feature is only available for account holders.',
  PAYMENT_HEADER: 'PAYMENT',
  ADD_CREDIT_OR_DEBIT_CARD: 'Add Credit/Debit Card',
  CREDIT_OR_DEBIT_CARD: 'Credit/Debit Card',
  CARD_OPTION: 'Card Option',
  CARD_NUMBER: 'Card number',
  EXPIRY_DATE: 'Exp. Date',
  CVV: 'CVV',
  NAME_ON_CARD: 'Name on card',
  BILLING_ADDRESS: 'Billing address',
  APT_SUITE: 'Apt/Suite',
  ZIP_CODE_PAYMENT: 'Zip code',
  MAKE_DEFAULT_CARD: 'Make default card',
  SAVE_CARD: 'Save Card',
  SAVE_CARD_GUEST: 'Confirm',
  AUTHENTICATION_ERROR: 'Authentication Error',
  OOPS: 'Oops!',
  PAS_CHANGE_SUCCESS_MESSAGE: 'Your password has been changed successfully',
  GRANTED: 'granted',
  DENIED: 'denied',
  NEW_LOCATION: 'New Location',
  NEW_LOCATION_CART_DIALOG_MESSAGE:
    'Changing your store location will clear all items from Shopping Cart and My List. Do you still want to change your store location?',
  CHANGE: 'Change',
  CHANGE_LOCATION: 'Change Location',
  SIGN_IN_CREATE_ACCOUNT: 'Sign In/Create Account',
  PRODUCT_FEATURES: 'Product Features',
  ELIGIBLE_FOR_SNAP: 'Eligible for SNAP',
  YOU_MIGHT_ALSO_LIKE: 'You Might Also Like',
  FOOD_STAMP_SUBTOTAL: 'SNAP Eligible Subtotal',
  SUBTOTAL: 'Subtotal',
  HANDLING_FEE: 'Handling Fee',
  FREIGHT_CHARGE: 'Freight Charge',
  TAX: 'Tax',
  TAX_FORGIVEN: 'Tax Forgiven',
  TOTAL_AMOUNT: 'Total Amount',
  SAVINGS: 'Savings',
  SEARCH_SALE_ITEMS: 'Search Sale Items',
  SEARCH_DEALS_ITEMS: 'Search Deals Items',
  REMOVE_SINGLE: 'Remove Single',
  ADD_NEW: 'Add New',
  UPDATE_PRODUCTS: 'Update Products',
  PRODUCTS: 'Products',
  ACCOUNT_DEACTIVATED: 'Your account has been deactivated',
  SUBSTITUTION_ALLOWED: 'Substitutions Allowed',
  SUBSTITUTION_SETTINGS: 'Substitution Settings',
  SNAP_ELIGIBILITY: 'SNAP Eligibility',
  REMOVE_FROM_ORDER: 'Remove from Order',
  REMOVE_FROM_LIST: 'Remove from List',
  REMOVE_FROM_ORDER_MESSAGE:
    'Are you sure you would like to remove the item from the order?',
  REMOVE_CAKE_FROM_ORDER_MESSAGE:
    'Are you sure you would like to remove the Custom Cake from your order?',
  REMOVE_CUPCAKE_FROM_ORDER_MESSAGE:
    'Are you sure you would like to remove the Custom Cupcake from your order?',
  REMOVE_DECORATION_FROM_ORDER:
    'Are you sure you would like to remove the Edible Decoration from your Custom Cake order?',
  REMOVE_FROM_LIST_MESSAGE:
    'Are you sure you would like to remove the item from the list?',
  CONTACT_INFORMATION: 'Contact Information',
  PICKUP_TIME: 'Pickup Window',
  DELIVERY_DATE: 'Delivery Date',
  DELIVERY_DATE_: 'Delivery date',
  DATE: 'Date',
  TIME: 'Time',
  ORDER_NOTIFICATION_PREFERENCE: 'Order notification preference',
  ALERT_TEXT_EMAIL: 'Alert, Text, and Email',
  SCHEDULE_PICKUP: 'Schedule Pickup',
  SPECIAL_INSTRUCTION: 'Special instructions (Optional)',
  OPTIONAL: '(Optional)',
  ADD_INSTRUCTION_HERE: 'Add instructions here...',
  ADD_PAYMENT_METHOD: 'Add payment method',
  REVIEW_ORDER: 'Review Order',
  SELECT_TIME: 'Please select a window',
  PLACE_ORDER: 'Place Order',
  WRONG_PHONE_NUMBER_ERROR:
    'Your order is not placed. Please use a valid contact number.',
  PROCEED_TO_CHECKOUT: 'Proceed to Checkout',
  REMOVE_ALL_ITEMS: 'Remove All',
  DELETE_ALL_CONFIRMATION: 'Are you sure you want to clear all notifications?',
  ARE_YOU_SURE_YOU_WANT_TO_REMOVE_ALL_ITEMS_FROM_LIST:
    'Are you sure you want to remove all items from list?',
  DECLINE: 'Decline',
  CONTINUE_AS_GUEST: 'Continue as Guest',
  CREATE_ACCOUNT_TO_GET_ADDITIONAL_SAVINGS:
    'Select to create an account and access more features',
  ALREADY_A_MEMBER: 'Already a member? ',
  TO_YOUR_ACCOUNT: 'to your account',
  GUEST_CHECKOUT_PASSWORD_REQUIREMENT:
    'Password Requirement: Minimum 8 characters including at least one upper case letter, lower case letter, number, and symbol.',
  ACCOUNT_ALREADY_EXISTS: 'Account Already Exists',
  CONNECTION_ERROR: 'Connection Error',
  CONNECTION_ERROR_MESSAGE:
    'Make sure that you are connected to internet and try again',
  DETAILS: 'DETAILS',
  SALE_DETAILS: 'SALE DETAILS',
  BUSH_DELIVERY: 'Bush Delivery',
  CURBSIDE_OR_HOME_DELIVERY: 'Curbside Pickup or Home Delivery',
  CURBSIDE_PICKUP: 'Curbside Pickup',
  HOME_DELIVERY: 'Home Delivery',
  REQUESTED_PICKUP_DATE: 'Requested Pickup date',
  PICKUP_DATE_AND_TIME: 'Pickup Date and Time',
  REQUESTED_DELIVERY_DATE: 'Requested Delivery date',
  REQUESTED_DELIVERY_TO_AIRLINE: 'Requested Delivery to Airline',
  DELIVERY_FEE: 'Delivery Fee',
  CART: 'Cart',
  EMPTY_CART_MESSAGE: 'Your cart is empty',
  CART_IS_EMPTY: 'Cart is Empty',
  DELIVERY_INFORMATION: 'Delivery Information',
  DELIVERY_ADDRESS: 'Delivery address',
  ADD_ADDRESS: 'Add address',
  SELECT_DELIVERY_OPTION: 'Select delivery option',
  BUSH_DELIVERY_INFORMATION: 'Bush Delivery Information',
  DESTINATION_VILLAGE: 'Destination Village',
  ADD_DESTINATION_VILLAGE: 'Add destination village',
  SELECT_DELIVERY_DATE: 'Select delivery date',
  SAVE_AND_CONTINUE: 'Save and Continue',
  MAKE_DEFAULT_ADDRESS: 'Make default delivery address',
  ITEMS: 'Items',
  ITEM: 'Item',
  CONFIRMATION: 'CONFIRMATION',
  ORDER_PLACED: 'Order Placed!',
  THANK_YOU_MESSAGE:
    ' Thanks for your order! We hope you enjoyed shopping with us.',
  DISCLAIMER: 'Disclaimer',
  DISCLAIMER_TEXT:
    'This order total is an estimate. Your final order total may change based on actual weights of items sold by weight, substitutions, or temporarily unavailable items. Food Stamp Subtotal, Taxes, Savings, and Freight/Handling Charges may also change based on the factors listed above.',
  TRANSACTION_RECORD: 'Transaction Record',
  CONTENT:
    'Content: include all transaction details provided by the payment processor (i.e. FiServ)',
  CUSTOMER_INFO: 'Customer Information',
  CREATE_MESSAGE_EMPTY_NAME: 'Please Enter List Name',
  //Order Estimated Amount
  ESTIMATED_TOTAL_TEXT: 'Estimated Total Amount',
  ESTIMATED_TOTAL_HEADING: 'Estimated Total Amount',
  ESTIMATED_TOTAL_DETAILS:
    'This order total is an estimate. Your final order total may change based on actual weights of items sold by weight, substitutions, or temporarily unavailable items. SNAP Eligible Subtotal, Taxes, Savings, and Freight/Handling Charges may also change based on the factors listed above.  Per USDA regulations, SNAP and EBT Cash transactions will never exceed the Estimated Order Total.',
  ESTIMATED_SAVINGS_TEXT: 'Savings',
  ESTIMATED_SAVINGS_HEADING: 'Savings',
  ESTIMATED_SAVINGS_DETAILS:
    'This savings total is an estimate. Your final savings total may change based on actual weights of items sold by weight, substitutions, or temporarily unavailable items.',
  ESTIMATED_TAX_TEXT: 'Tax',
  ESTIMATED_TAX_HEADING: 'Tax',
  ESTIMATED_TAX_DETAILS:
    'This tax total is an estimate. Your final tax total may change based on actual weights of items sold by weight, substitutions, or temporarily unavailable items.',
  ESTIMATED_FREIGHT_TEXT: 'Freight Charge',
  ESTIMATED_FREIGHT_HEADING: 'Freight Charge',
  ESTIMATED_TAX_FORGIVEN: 'Tax Forgiven',
  ESTIMATED_FREIGHT_DETAILS:
    'This freight charge total is an estimate. Your final freight charge total may change based on actual weights of items sold by weight, substitutions, or temporarily unavailable items.',
  ESTIMATED_SUBTOTAL: 'Subtotal',
  DIFF_LOCATION_FOUND: 'Different location found',
  DIFF_LOCATION_FOUND_MESSAGE:
    'Your current location does not match your home store location. Would you like to change your store?',
  ORDER_STATUS: 'Order Status',
  SUBMITTED: 'Submitted',
  ORDER_COMPLETED: 'Order Completed',
  TRACKING_NUMBER: 'Tracking Number: ',
  ORDER_HISTORY_DIALOG_MESSAGE:
    'Re-ordering this order will change your current store location to the store location of the original order. It will also clear all items from Shopping Cart and My List. Do you still want to re-order this order?',
  ORDERS_ELIGIBLE_FOR_REFUND: 'Orders Eligible for Refund',
  SUBMITTED_REFUND_REQUESTS: 'Submitted Refund Requests',
  SUBMITTED_REQUESTS: 'SUBMITTED REQUESTS',
  REASONS: 'Reason',
  VIEW_ORDER: 'View Order',
  REQUEST_CONFIRMED: 'Request Confirmed',
  REQUEST_CONFIRMED_MESSAGE:
    'We are reviewing your request. You will be notified when your request has been reviewed. Thank you for shopping with us.',
  REFUND_REQUEST_NO: 'Refund Request #',
  STATUS: 'Status:',
  REQUEST_SENT: 'Request Sent:',
  ORDER_REFERENCE: 'Order Reference: #',
  ORDER_STORE: 'Order Store:',
  ORDER_TYPE: 'Order Type:',
  TRANSACTION_RECORD_MESSAGE:
    'Content: include all transaction details provided by the payment processor (i.e. FiServ)',
  CUSTOMER_INFORMATION: 'Customer Information',
  REFUND_PAYMENT_METHOD: 'Refund Payment Method',
  TELL_US_WHY: 'Tell us why',
  VISA_ENDING: 'Visa ending in 1234',
  CONFIRM_REFUND_REQUEST: 'Confirm Refund Request',
  CAKES_AND_PIES: 'CAKES AND PIES',
  CUSTOMIZE: 'Customize',
  CUSTOMIZE_YOUR_CAKE: 'Customize Your Cake',
  CUSTOMIZE_YOUR_CUPCAKE: 'Customize Your Cupcakes',
  CAKE_FLAVOR: 'Cake Flavor (Required)',
  CUPCAKE_FLAVOR: 'Cupcake Flavor (Required)',
  CAKE_FILLING: 'Cake Filling (Required)',
  EDITABLE_DECORATION: 'Edible Decoration (Required)',
  WRITTEN_MESSAGE: 'Written Message',
  SPECIAL_INSTRUCTIONS: 'Special Instructions',
  ENTER_SPECIAL_INSTRUCTIONS_I: 'Enter Special Instructions',
  ENTER_EDIBLE_DECORATION_DESCRIPTION: 'Enter Edible Decoration Description',
  ENTER_FROSTING_FLAVOUR_DESCRIPTION:
    'Enter Frosting Flavor Request. The store will contact you if your requested flavor is unavailable.',
  FROSTING_FLAVOR_PLACEHOLDER: 'Enter Frosting Flavor Request',
  FROSTING_FLAVOR: 'Frosting Flavor (Required)',
  EMAIL_IMAGE_TO_STORE: 'I will email my image to the store',
  ENTER_EDIBLE_DECORATION_REQUEST: 'Enter edible decoration request',
  EDIBLE_DECORATION_REQUEST_DESCRIPTION:
    'Enter edible decoration request. The store will contact you if your requested flavor is unavailable.',
  SELECT_FLAVOR: 'Please select a flavor',
  SELECT_FILLING: 'Please select a filling',
  SELECT_DECORATION: 'Please select the decoration',
  ENTER_MESSAGE: 'Please enter the message',
  ENTER_MESSAGE_II: 'Enter Message',
  ENTER_SPECIAL_INSTRUCTIONS: 'Please enter any special instructions',
  ADD_TO_CART: 'Add to Cart',
  EDIBLE_DECORATION_TYPE: 'Edible Decoration Type (Required)',
  OTHER: 'Other',
  OTHER_FROSTING_FLAVOR: 'Other Frosting Flavor',
  EMAIL_IMAGE_INSTRUCTIONS: 'Email Image Instructions',
  CUSTOM_CAKE_LEAD_TIME: 'Custom Cake Lead Time',
  PARTY_TRAY_LEAD_TIME: 'Party Tray Lead Time',
  ENTER_REQUEST: 'Enter Request',
  DECORATION_EMAIL_INSTRUCTIONS_I:
    'Once your order is placed, please email your image to',
  DECORATION_EMAIL_INSTRUCTIONS_II:
    'with your order number and “Cake Image” in the subject line.',
  CAKE_LEAD_TIME_MESSAGE:
    'Please note that custom cakes may take up to 3 business days (not including weekends) to be prepared. Your order will be held until your custom cake is ready.',
  PARTY_TRAY_TIME_MESSAGE:
    'Please note that party tray may take up to 3 business days (not including weekends) to be prepared. Your order will be held until your party tray is ready.',
  SNAP: 'SNAP',
  EDIBLE_DECORATION_DESCRIPTION: 'Edible Decoration Description',
  NONE: 'None',
  CALL_CUSTOMER_SERVICE: 'Call Customer Service Toll Free at',
  CUSTOMIZE_CAKE_DESC:
    'To create multiple orders of the same cake or cupcake item, please complete your initial customization and then select Customize again from the item menu.\n' +
    '\n' +
    'For cakes with custom images or other special instructions, we encourage you to call your AC store Bakery to confirm the details. Your AC Bakery may also contact you to confirm certain details.\n' +
    '\n' +
    'For Curbside Pickup custom cake orders, please indicate in the Special Instructions box if you have a specific time by which you need to pick up your custom cake.',
  SELECT: 'Select',
  SELECTED: 'Selected',
  NEXT_DESCRIPTION: 'Next: Description',
  CLOSE: 'Close',
  GUEST_INFO: 'Guest Information',
  PHONE_NUM_OPTIONAL: 'Phone Number (Optional)',
  FEEDBACK: 'Feedback',
  ADD_TO_LIST: 'Add to List',
  ADD_TO_UNDER_LIST: 'Add to\nList',
  OPEN_SETTINGS_TEXT:
    'Please open settings to allow notification.\nDo you want to open settings?',
  OPEN_SETTINGS: 'Open Settings',
  EMAIL_VERIFICATION: 'Email Verification',
  VERIFY_Email: 'Verify Email',
  VERIFICATION_LINK_SENT: 'A verification link has been sent to your email,',
  CLICK_VERIFICATION_LINK:
    'Please click the link to verify your account. \n\nNote: It may take up to five minutes to receive the verification email.',
  OPEN_EMAIL_TO_VERIFY: 'Open Email to Verify',
  RESEND_VERIFICATION_LINK: 'Resend Verification Link',
  VERIFY_LATER: 'Verify Later',
  QUALTRICS: 'Qualtrics',
  REFUND_SUBTOTAL: 'Refund Subtotal',
  REFUND_TOTAL: 'Refund Total',
  SNAP_ELIGIBLE_SUBTOTAL: 'SNAP Eligible Subtotal',
  NO_INTERNET_CONNECTION: 'No internet connection. Please try again later.',
  RESEND_CODE: 'Resend code',
  RESEND_IN: 'Resend code in 00:',
  VERIFY: 'Verify',
  CODE_SENT: 'Verification code has been sent successfully',
  ENTER_VERIFICATION_CODE: 'Enter Verification Code',
  MAX_SALE_LIMIT: 'Max Sale Item Limit:',
  SNAP_OPTIONS: 'EBT Options',
  FOOD_BENEFITS: 'Food Benefits',
  EBT_CASH_BENEFITS: 'EBT Cash Benefits',
  GIFT_CARD_ENDING_IN: 'Gift Card ending in',
  VW_ENDING_IN: 'Virtual Wallet ending in',
  CARD_ENDING_IN: 'Card ending in',
  GIFT_CARD: 'Gift Card',
  TOOTAL_AVAILABLE_BALANCE: 'Total Available Balance: $',
  ENTER_AMOUNT: 'Enter amount',
  SUBMIT_SNAP_PAYMENT: 'Submit EBT Payment',
  SUBMIT_GIFT_CARD_PAYMENT: 'Submit Gift Card Payment',
  GC_PIN_NUMBER: 'Gift Card PIN Number',
  GC_PIN: 'Enter PIN Number',
  CONTINUE_GIFT_CARD_OPTIONS: 'Continue: Gift Card Options',
  REMAINING_ORDER_TOTAL: 'Remaining Order Total:',
  REMAINING_ORDER_TOTAL_II: 'Remaining Order Total',
  REMAINING_SNAP_TOTAL: 'Remaining SNAP Eligible Order Total:',
  ON_BOARDING1_HEADER: 'Welcome to the \nAlaska Commercial App!',
  ON_BOARDING1_TEXT:
    'Shop your AC store online. Enjoy in-store prices when you shop in the app.',
  ON_BOARDING2_HEADER: 'Departments',
  ON_BOARDING2_TEXT: 'Browse by Department or search for your favorite items.',
  ON_BOARDING3_HEADER: 'Add to Cart or List',
  ON_BOARDING3_TEXT:
    'Add items to your cart with a click or save them to a list for later.',
  ON_BOARDING3_SUBTEXT:
    '*To access Lists and History,\n  please create an account',
  ON_BOARDING4_HEADER: 'Order a Custom Cake',
  ON_BOARDING4_TEXT:
    'Go to Cakes and Pies in the Bakery department, to create your custom cake.',
  ON_BOARDING5_HEADER: 'Checkout',
  ON_BOARDING5_TEXT: 'Checkout and pay online with multiple payment options.',
  START_SHOPPING: 'Start Shopping',
  CARD_INACTIVE: 'Card Inactive. Do you want to add a new card?',
  CARD_EXPIRED: 'Card Expired. Do you want to add a new card?',
  SNAP_CARD_ENDING_IN: 'EBT Card ending in',
  AMOUNT_EXCEEDS_SNAP_SUBTOTAL:
    'Amount Entered Exceeds SNAP Food Eligible Subtotal',
  AMOUNT_EXCEEDS_AVAILABLE_FOOD_BALANCE:
    'Amount Entered Exceeds Available SNAP Food Balance',
  AMOUNT_EXCEEDS_AVAILABLE_CASH_BALANCE:
    'Amount Entered Exceeds Available EBT Cash Balance',
  AMOUNT_EXCEEDS_SNAP_CASH_SUBTOTAL:
    'Amount Entered Exceeds EBT Cash Eligible Subtotal',
  AMOUNT_ENTERED_EXCEEDS_REMAINING_ORDER_TOTAL:
    'Amount Entered Exceeds Remaining Order Total',
  AMOUNT_ENTERED_EXCEEDS_AVAILABLE_VIRTUAL_WALLET_BALANCE:
    'Amount Entered Exceeds Available Virtual Wallet Balance',
  AMOUNT_ENTERED_EXCEEDS_AVAILABLE_GC_BALANCE:
    'Amount Entered Exceeds Available Gift Card Balance',
  AMOUNT_ENTERED_EXCEEDS_AVAILABLE_STA_BALANCE:
    'Amount Entered Exceeds Available Store Charge Account Balance',
  ENTER_VALID_AMOUNT: 'Please enter a valid amount',
  THIS_TRANSACTION_ONLY: 'Add to this transaction only',
  INVALID_SNAP_PIN:
    'Please enter a valid PIN or call the number on the back of your EBT Card for assistance.',
  INVALID_SNAP_CARD:
    'Please enter a valid EBT Card number or call the number on the back of your EBT Card for assistance.',
  INVALID_DEBIT_CARD:
    'Please enter a valid Card number or call the number on the back of your Card for assistance.',
  INVALID_SNAP_CARD_PIN:
    'Please enter a valid EBT Card number and PIN or call the number on the back of your EBT Card for assistance.',
  INVALID_GC_NUMBER:
    'AC Gift Card Number is invalid. Please enter a valid card number.',
  INVALID_STA_NUMBER:
    'Store Charge Account Number is invalid. Please enter a valid card number.',
  SNAP_REMAINING_BALANCE: 'SNAP Food Balance Remaining:',
  CASH_REMAINING_BALANCE: 'EBT Cash Balance Remaining:',
  OPEN_VIRTUAL_WALLET: 'Open Virtual Wallet',
  AC_SHOPPING_ACCOUNT:
    'You’ve successfully created an Alaska Commercial shopping account!',
  AC_SIGN_UP_REWARD:
    'As thanks for shopping with us, we’ve loaded $10 into your Virtual Wallet. You can use these' +
    ' rewards when checking out in the app or show the barcode in-store to use it like an AC gift card.',
  APPLIED_FULL_AMOUNT:
    'You have applied the full estimated order amount. Your credit card will only be charged if the order total increases due to substitutions or random weight variations.',
  GC_APPLIED_FULL_AMOUNT:
    'You have applied the full estimated order amount to your Gift Card. Your credit card will only be charged if the order total increases due to substitutions or random weight variations.',
  SNAP_APPLIED_FULL_AMOUNT:
    'You have applied the full estimated order amount to your EBT Card. Your credit card will only be charged if the order total increases due to substitutions or random weight variations.',
  STA_APPLIED_FULL_AMOUNT:
    'You have applied the full estimated order amount to your Store Charge Account. Your credit card will only be charged if the order total increases due to substitutions or random weight variations.',
  VW_APPLIED_FULL_AMOUNT:
    'You have applied the full estimated order amount to your Virtual Wallet. Your credit card will only be charged if the order total increases due to substitutions or random weight variations.',
  ADD_STA: 'Add Store Charge Account',
  ADD_STA_ERROR: 'Please enter a first and last name or an organization name',
  STA_FIRST_NAME: 'First name',
  STA_LAST_NAME: 'Last name',
  STA_ORGANIZATION: 'Organization name',
  SAVE_CHARGE_ACCOUNT: 'Save Charge Account',
  SAVE_CHARGE_ACCOUNT_GUEST: 'Add Store Charge Account',
  CHARGE_ACCOUNT_NUMBER: 'Charge account number',
  PLAN_TYPE: 'Plan type',
  STA_ENDING_IN: 'Store Charge Account ending in',
  ACCOUNT_ENDING_IN: 'Account ending in',
  SNAP_ELIGIBLE: 'SNAP Eligible',
  ADJUSTMENT_AMOUNT: 'Adjustment Amount',
  STORE_CHARGE_ACCOUNT: 'Store Charge Account',
  STA_SAVED: 'Saved Store Charge Account',
  STA_CHARGE_FULL: 'Charge Full Remaining Purchase Amount',
  SUBMIT_STA: 'Submit Store Charge Account Payment',
  PURCHASE_ORDER_NUMBER: 'Purchase Order Number(Required)',
  NO_PRODUCT_FOUND: 'Item not found',
  DO_YOU_WANT_TO_LOG_IN: 'Do you want to Log in?',
  ALREADY_MEMBER_SO_SIGN_IN: 'Already a Member? Sign in to your Account',
  OR: 'OR',
  SCHEDULE_DELIVERY: 'Schedule Delivery',
  DESTINATION_AIRPORT: 'Destination Airport',
  NO_PRODUCT_FOUND_MESSAGE:
    'This item is not available online from the AC store selected in your online account.\n\nWant to browse the online catalog for your AC store? Tap the Shop or On Sale buttons.',
  BACK_TO_LOGIN: ' Back to Login',
  EXIT: 'Exit',
  SAVE_CARD_CHECKOUT: 'Save Card Information for Future Transactions',
  // swiper_header1: 'Freshness you can count on for every meal.',
  swiper_header1: 'Get fresh vegetables\nfrom your AC store!',

  swiper_subHeading1: 'Get fresh vegetables from your AC store.',
  // swiper_header2: 'High-quality meats for your winter feasts.',
  swiper_header2: 'Stock up on \nbeef and steaks!',


  swiper_subHeading2: 'High-quality meats for your winter feasts.',
  // swiper_header3: 'Keep your milk company with delicious cookies.',
  swiper_header3: 'Snack happy with\ndelicious cookies!',



      swiper_subHeading3: 'Shop your favorite brands!',
  LOCATION_AND_BANDWIDTH: 'Location and Bandwidth',
  MY_ACCOUNT: 'My Account',
  MY_PROFILE: 'My Profile',
  REFUND_REQUEST_S: 'Refund Request',
  POPULAR_ITEMS_IN_YOUR_AREA: 'Popular Items in Your Area',
  CATEGORIES: 'Categories',
  ADD_TO_LIST_CAPITAL: 'ADD TO LIST',
  xoxox: 'xixoxo',
};

export const SEARCH_DEBOUNCE_DELAY = 700;
