import {Platform, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {FONTS, getFontSize, COLORS} from './index';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerBackImage: {
    tintColor: COLORS.WHITE,
    height: 24,
    width: 24,
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: COLORS.GRAY0_5,
    marginTop: hp('2%'),
    alignItems: 'center',
    justifyContent: 'center',
    marginStart: wp('6%'),
  },
  dateText: {
    fontSize: getFontSize(15),
    fontFamily: FONTS.MEDIUM,
    fontStyle: 'normal',
    letterSpacing: -0.3,
    color: '#8a8a8e',
  },
  btnWrapper: {
    width: '90%',
    backgroundColor: COLORS.DISABLE_BUTTON_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: 50,
    borderRadius: wp('2%'),
    marginTop: hp('2%'),
  },
  settingsWrapper: {
    backgroundColor: COLORS.WHITE,
    marginTop: hp('1.7%'),
    paddingBottom: hp('2%'),
  },
  textWrapper: {
    // marginStart: wp('6%'),
    // marginEnd: wp('6%'),
    marginTop: hp('3%'),
  },
  textHeader: {
    fontFamily: 'SFProDisplay-Semibold',
    fontSize: Platform.OS === 'ios' ? 18 : 16,
    paddingBottom: hp('1%'),
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 22,
    color: '#000000',
    marginStart: wp('6%'),
  },
  locationText: {
    fontFamily: 'SFProDisplay-Regular',
    fontSize: 17,
    marginTop: hp('1.5%'),
    color: COLORS.GRAY_TEXT_0_78,
  },
  nearByText: {
    fontFamily: 'SFProDisplay-Regular',
    fontSize: 17,
    marginTop: hp('.8%'),
  },
  fieldWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp('2%'),
  },
  bandwidthWrapper: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  bandwidthText: {
    fontSize: 19,
    color: COLORS.BLACK,
    fontFamily: 'SFProDisplay-Regular',
  },

  settingTextStyle: {
    fontFamily: 'SFProDisplay-Regular',
    color: COLORS.BLACK,
    fontSize: Platform.OS === 'ios' ? 19 : 17,
    letterSpacing: -0.28,
    fontWeight: Platform.OS === 'ios' ? '400' : null,
    fontStyle: 'normal',
    lineHeight: 22,
  },
  checkboxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('2%'),
    justifyContent: 'space-between',
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  singleBlockWrapper: {
    backgroundColor: COLORS.WHITE,
    justifyContent: 'center',
    height: 60,
  },
  singleBlockTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('6%'),
  },
  productCard: {
    flexDirection: 'row',
    paddingBottom: hp('2%'),
    marginEnd: wp('4%'),
  },
  productBannerView: {
    width: '18%',
  },
  productBannerImage: {
    width: 100,
    height: 42,
  },
  productImageView: {
    marginStart: wp('1%'),
  },
  productImage: {
    width: 100,
    height: 75,
  },
  productInformationView: {
    width: '65%',
    marginStart: wp('10%'),
    justifyContent: 'flex-start',
  },
  productPriceView: {
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  productSalePrice: {
    fontSize: Platform.OS === 'ios' ? 19 : 17,
    fontFamily: 'SFProDisplay-Semibold',
  },
  productDiscountPrice: {
    marginStart: wp('2%'),
    textDecorationLine: 'line-through',
    fontSize: Platform.OS === 'ios' ? 14 : 12,
  },
  productDescriptionText: {
    marginTop: 8,
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    color: COLORS.BLACK,
  },
  stepperView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLORS.BLACK_40,
    borderWidth: 1.5,
    width: 120,
    height: 38,
    borderRadius: 6,
    marginTop: hp('2%'),
  },
  stepperCellView: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperCellText: {
    fontSize: 18,
    color: COLORS.GRAY_4,
    alignSelf: 'center',
  },
  verticalSeparator: {
    height: 38,
    width: 1.5,
    backgroundColor: COLORS.BLACK_40,
  },
  stepperValueView: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  stepperValueText: {
    fontSize: 18,
    width: 38,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  addToCartCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.MAIN,
    width: 90,
    height: 38,
    borderRadius: 6,
    marginTop: hp('2%'),
    marginStart: wp('4%'),
  },
  addToCartTextWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  addToCartText: {
    color: COLORS.WHITE,
    textAlign: 'center',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
  },
  cartImageWrapper: {
    width: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartImage: {
    width: 17,
    height: 17,
  },
  notAvailableProducts: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: hp('4%'),
    marginTop: hp('2%'),
  },
  notAvailableTextWrapper: {
    alignSelf: 'center',
  },
  notAvailableText: {
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    color: COLORS.GRAY_4,
    textAlign: 'center',
  },
  listIconWrapper: {
    width: '10%',
    marginTop: 15,
  },
  listIcon: {
    width: 20,
    height: 20,
  },
  modalView: {
    justifyContent: 'flex-end',
    margin: 0,
    ...Platform.select({
      android: {
        bottom: 0,
        width: '100%',
        position: 'absolute',
      },
    }),
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    paddingBottom: hp('5%'),
    maxHeight: hp('70%'),
  },
  listRow: {
    width: '92%',
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  createListText: {
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
    marginStart: wp('2%'),
  },
  separator: {
    backgroundColor: COLORS.GRAY0_5,
    height: 1,
    width: '90%',
    alignSelf: 'center',
  },
  modalBtnWrapper: {
    width: '90%',
    backgroundColor: COLORS.DISABLE_BUTTON_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: 50,
    borderRadius: wp('2%'),
    marginTop: hp('1%'),
  },
  filterModalContent: {
    backgroundColor: 'white',
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    paddingBottom: hp('5%'),
  },
  filterTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterText: {
    fontFamily: 'SFProDisplay-Semibold',
    fontSize: Platform.OS === 'ios' ? 17 : 15,
  },
  clearWrapper: {
    width: 150,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  clear: {
    color: COLORS.MAIN,
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontFamily: 'SFProDisplay-Medium',
  },
  depWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp('3%'),
  },

  modalDivider: {
    borderBottomColor: COLORS.GRAY_1,
    borderBottomWidth: 1,
    marginTop: hp('1.5%'),
    marginBottom: hp('1.5%'),
  },
  sortByWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp('2%'),
  },
  priceSortText: {
    color: COLORS.GRAY_4,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
    marginTop: hp('.5%'),
  },
  depText: {
    color: COLORS.BLACK,
    fontSize: Platform.OS === 'ios' ? 17 : 15,
    fontFamily: 'SFProDisplay-Regular',
  },
  view: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  listNameWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: widthPercentageToDP('2%'),
    marginStart: widthPercentageToDP('6%'),
    paddingEnd: widthPercentageToDP('6%'),
  },
  listNameText: {
    fontSize: getFontSize(18),
    fontFamily: FONTS.SEMI_BOLD,
    fontStyle: 'normal',
    letterSpacing: 0,
    color: COLORS.BLACK,
    maxWidth: '68%',
  },
  creationDateWrapper: {
    alignItems: 'flex-start',
    marginStart: 10,
    justifyContent: 'flex-start',
  },
  creationDateText: {
    color: COLORS.GRAY_TEXT,
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    // fontWeight: Platform.OS === 'ios' ? '500' : 'bold',
    alignSelf: 'flex-start',
    fontFamily: 'SFProDisplay-Semibold',
  },
  editText: {
    fontSize: getFontSize(13),
    fontFamily: FONTS.MEDIUM,
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: COLORS.MAIN,
  },
  cartActionsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp('2%'),
    marginStart: wp('6%'),
    marginEnd: wp('6%'),
  },
  addAllAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.MAIN,
    width: 110,
    height: 38,
    borderRadius: 6,
  },
  removeAllText: {
    color: COLORS.MAIN,
    fontSize: Platform.OS === 'ios' ? 15 : 13,
    fontWeight: '500',
    fontFamily: 'SFProDisplay-Regular',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
  },
  viewMargin: {height: hp('1.5%'), backgroundColor: '#f4f4f4'},
  topBorderedView: {
    borderBottomColor: COLORS.GRAY_1,
    borderBottomWidth: 1,
  },
  listEmptyComponentView: {
    flex: 1,
    height: hp('60%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightArrowStyle: {
    width: 8,
    height: 25,
    alignSelf: 'flex-end',
  },
  modalItemRow: {flexDirection: 'row', alignItems: 'center'},
  sectionDivider: {
    height: hp('1.7%'),
    backgroundColor: '#f4f4f4',
  },
  searchComponentWrapper: {
    height: 75,
    backgroundColor: COLORS.MAIN,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
