// Define action types
export const GET_LIST = 'GET_LIST';
export const ADD_TO_LIST = 'ADD_TO_LIST';
export const REMOVE_LIST = 'REMOVE_LIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_CART_ITEMS = 'CHANGE_CART_ITEMS';
export const UPDATE_CART_ITEMS_COUNT = 'UPDATE_CART_ITEMS_COUNT';
export const UPDATE_ZIP_CODE_DETAILS = 'UPDATE_ZIP_CODE_DETAILS';
export const SET_ELIGIBLE_REFUND_ORDERS = 'SET_ELIGIBLE_REFUND_ORDERS';
export const CHANGE_LIST = 'CHANGE_LIST';
export const SAVE_ZIP_CODES = 'SAVE_ZIP_CODES';
export const CHANGE_NOTIFICATIONS_SETTINGS = 'CHANGE_NOTIFICATIONS_SETTINGS';
export const SAVE_PREVIOUS_SEARCHES = 'SAVE_PREVIOUS_SEARCHES';
export const ADD_PAYMENT_OPTION = 'ADD_PAYMENT_OPTION';
export const CHANGE_PAYMENT_OPTION = 'CHANGE_PAYMENT_OPTION';
export const SET_DEFAULT_PAYMENT_OPTION = 'SET_DEFAULT_PAYMENT_OPTION';
export const CHANGE_SELECTED_DELIVERY_SEGMENT = 'CHANGE_SELECTED_DELIVERY_SEGMENT';
export const SET_DELIVERY_TYPE = 'SET_DELIVERY_TYPE';
export const SET_SEGMENTS = 'SET_SEGMENTS';
export const CHANGE_AUTH_ERROR_DIALOG = 'CHANGE_AUTH_ERROR_DIALOG';
export const SET_NOTIFICATION_ALLOWED = 'SET_NOTIFICATION_ALLOWED';
export const CHANGE_API_ERROR_DIALOG = 'CHANGE_API_ERROR_DIALOG';
export const SET_TIME_FORMAT = 'SET_TIME_FORMAT';
export const SET_NOTIFICATION_BADGE = 'SET_NOTIFICATION_BADGE';
export const TOGGLE_API_ERROR_DIALOG = 'TOGGLE_API_ERROR_DIALOG';
export const TOGGLE_UNDER_MAINTENANCE = 'TOGGLE_UNDER_MAINTENANCE';
export const CHANGE_PROMO_VISIBILITY = 'CHANGE_PROMO_VISIBILITY';
export const SET_DEEPLINK_DATA = 'SET_DEEPLINK_DATA';

//Auth Actions
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const SAVE_BEARER_TOKEN = 'SAVE_BEARER_TOKEN';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';
export const SET_LOGIN_TOKENS = 'SET_LOGIN_TOKENS';

export const SET_IS_BIOMETRICS_MODAL = 'SET_IS_BIOMETRICS_MODAL';
export const LOGOUT = 'LOGOUT';
export const ALL_DEPARTMENTS = 'ALL_DEPARTMENTS';
export const DISABLED_DATES = 'DISABLED_DATES';
